### ISSUE TITLE
Feature: Add input option to control `pull requests` comment

### ISSUE THREAD

**Issue by benyboy84** [benyboy84/Bash#1]
### inputs: comment

Having an input that controls whether or not a comment is created in the pull request would be a good feature to add to this GitHub Action.

```yaml
  comment:
    description: 'Whether or not to comment on GitHub pull requests. Defaults to `false`.'
    required: false
    default: false
    type: boolean
```
